spring:
  application:
    name: 'gateway-service'

server:
  port: 8900

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/