package com.tastyfood.order.service.domain;

public enum OrderEvent {

    VALIDATE, VALIDATION_SUCCESS, VALIDATION_FAILED,
    PROCESS_PAYMENT, PAYMENT_SUCCESS, PAYMENT_FAILED,
    UPDATE_INVENTORY, INVENTORY_UPDATE_SUCCESS, INVENTORY_UPDATE_FAILED,
    ACCEPT, ACCEPTED, FAILED,
    CANCEL, DELIVER

}
